version: '3.8'

services:
  rendezvousms:
    build:
      context: ./rendezvousms
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  productms:
    build:
      context: ./patientms
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - mynetwork

  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    networks:
      - mynetwork

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8076:8076"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
