version: '3.8'

services:
  rendezvousms:
    build:
      context: ./rendezvousms
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    depends_on:
      - config-server
      - edgemicroservices
      - zookeeper
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rdvdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://edgemicroservices:8760/eureka/

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rdvdb
    networks:
      - mynetwork

  patientms:
    build:
      context: ./patientms
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - mynetwork
    depends_on:
      - config-server
      - edgemicroservices
      - zookeeper
      - kafka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://edgemicroservices:8760/eureka/

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    networks:
      - mynetwork
  edgemicroservices:
    image: manelterzi/edgemicroservices
    container_name: edgemicroservices
    ports:
      - "8760:8760"
    networks:
      - mynetwork
    depends_on:
      - config-server
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8076:8076"
    networks:
      - mynetwork
    depends_on:
      - config-server
      - edgemicroservices
      - rendezvousms
      - patientms

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - mynetwork
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
